language: php

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: trusty
    - php: 5.5.9
      dist: trusty
    - php: 5.5
      dist: trusty
    - php: 5.6
      dist: xenial
    - php: 7.0
      dist: xenial
    - php: 7.1
      dist: xenial
    - php: 7.2
      dist: xenial
    - php: 7.3
      dist: xenial
    - php: 7.4
      dist: xenial
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit -d error_reporting=24575 --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
